spring:
    profiles:
        include: swagger,local
    application:
        name: knowledge-session
    data:
        jpa:
            repositories:
                enabled: false
    datasource:
        driver-class-name: org.postgresql.Driver
        tomcat:
            initial-size: 34
            max-active: 377
            max-idle: 233
            max-wait: 10000
            min-evictable-idle-time-millis: 55000
            min-idle: 89    
    jpa:
        database: POSTGRESQL
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
    jackson:
        serialization:
            WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
            write-dates-as-timestamps: false
            fail-on-empty-beans: false
        deserialization:
            READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false   
    http:
        multipart:
            max-file-size: 900MB
            max-request-size: 900MB
            enabled: true
management:
    security:
        enabled: false